### ISSUE TITLE
Ande está el README??

### ISSUE THREAD

**Issue by averdones** [sqr/dota-leaderboard#1]
No me queda claro el mensaje de algunos commits kekw.

**Comment by sqr** [comment]
> 
> 
> No me queda claro el mensaje de algunos commits kekw.

Lolete no es un buen mensaje de commit? lulw

**Comment by averdones** [comment]
> > No me queda claro el mensaje de algunos commits kekw.
> 
> Lolete no es un buen mensaje de commit? lulw

No es lo suficientemente PEPOCHO

**Comment by sqr** [comment]
> 
> 
> > > No me queda claro el mensaje de algunos commits kekw.
> > 
> > 
> > Lolete no es un buen mensaje de commit? lulw
> 
> No es lo suficientemente PEPOCHO

está usted reportado a la polisía del flow

**Comment by sqr** [comment]
Added Readme.

Check daa8ad6
